pipeline {
agent any



stages {
stage('git repo & clean') {
steps {
  //bat "rmdir /s /q SpringBoot-RestAPI Pipeline"
  bat "git clone https://github.com/sugammehra/Spring-boot.git"
  bat "mv clean -f SpringBoot-RestAPI Pipeline"
}
}
stage('install') {
steps {
  bat "mvn install -f SpringBoot-RestAPI Pipeline"
}
}
stage('test') {
  steps {
  bat "mvn test -f SpringBoot-RestAPI Pipeline"
  }
}
  stage('package') {
  steps {
  bat "mvn package -f SpringBoot-RestAPI Pipeline"
  }
}
  
}
}
